### ISSUE TITLE
run_analysis doesn't work in Octave

### ISSUE THREAD

**Issue by davisking** [votchallenge/vot-toolkit#34]
Octave's version of unique() doesn't support the stable option.  So when you run run_analysis you get this output: 
```
octave:6> run_analysis
Initializing VOT environment ...
Compiling MEX files ...
error: unique: invalid option
error: called from:
error:   /usr/share/octave/3.8.1/m/set/unique.m at line 58, column 9
error:   /home/davis/temp/new-vot-toolkit/tracker/create_trackers.m at line 23, column 13
error:   /home/davis/temp/new-vot-toolkit/working_dir/run_analysis.m at line 10, column 10
```

**Comment by davisking** [comment]
If I comment out the unique call (which isn't needed since the inputs are already unique in my case) and run run_analysis I get this output (after a whole bunch of warnings about division by zero):
```
...
warning: division by zero
warning: division by zero
warning: division by zero
warning: division by zero
warning: division by zero
warning: division by zero
warning: division by zero
        Processing tracker ncc ...
  Writing ranking table ...
  Writing ranking details for experiment baseline ...
error: 'fields' undefined near line 51 column 19
error: called from:
error:   /home/davis/temp/new-vot-toolkit/utilities/struct_merge.m at line 51, column 17
error:   /home/davis/temp/new-vot-toolkit/utilities/struct_merge.m at line 38, column 16
error:   /home/davis/temp/new-vot-toolkit/utilities/create_table_cell.m at line 7, column 16
error:   /home/davis/temp/new-vot-toolkit/report/report_ranking.m at line 314, column 53
error:   /home/davis/temp/new-vot-toolkit/report/report_ranking.m at line 137, column 13
error:   /home/davis/temp/new-vot-toolkit/report/report_challenge.m at line 70, column 25
error:   /home/davis/temp/new-vot-toolkit/working_dir/run_analysis.m at line 16, column 1
```

**Comment by lukacu** [comment]
Thanks for the report, I will have to investigate the issue a bit more. We have tested the toolkit for the VOT2014 challenge, but since then there have been a number of changes and perhaps some of those introduced incompatibilities. I will try to test it today.

**Comment by lukacu** [comment]
One more thing: how many trackers did you include in the analysis? Many types of analysis are not supported for only one tracker, so use publicly available results of at least one more tracker.

**Comment by davisking** [comment]
I tried it with 2 trackers as well and got the same error.

**Comment by lukacu** [comment]
I have fixed `struct_merge.m`, can you try if the procedure works now? Mind that some parts of the analysis may be a bit complex for Octave (the original idea was that only the execution of the experiments is Octave compatible, but I will try to fix any problems if they are not too complex).

**Comment by davisking** [comment]
No problem.  It's getting farther now but still hitting an error.  Here is the new output:
```
octave:3> run_analysis
Initializing VOT environment ...
Compiling MEX files ...
WARNING: No configuration for tracker NCC found
WARNING: No configuration for tracker DSST found
Generating competition report
  Speed report ...
    Performing speed analysis ...
  Ranking analysis for experiment baseline ...
      Processing selector label_camera_motion ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_illum_change ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_occlusion ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_size_change ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_motion_change ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_empty ...
        Processing tracker NCC ...
        Processing tracker DSST ...
  Ranking analysis for experiment region_noise ...
      Processing selector label_camera_motion ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_illum_change ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_occlusion ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_size_change ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_motion_change ...
        Processing tracker NCC ...
        Processing tracker DSST ...
      Processing selector label_empty ...
        Processing tracker NCC ...
        Processing tracker DSST ...
  Writing ranking table ...
  Writing ranking details for experiment baseline ...
  Writing ranking details for experiment region_noise ...
Failures report ...
  Failure analysis for experiment baseline ...
    Processing sequence ball ...
    Processing sequence basketball ...
    Processing sequence bicycle ...
    Processing sequence bolt ...
    Processing sequence car ...
    Processing sequence david ...
    Processing sequence diving ...
    Processing sequence drunk ...
    Processing sequence fernando ...
    Processing sequence fish1 ...
    Processing sequence fish2 ...
    Processing sequence gymnastics ...
    Processing sequence hand1 ...
    Processing sequence hand2 ...
    Processing sequence jogging ...
    Processing sequence motocross ...
    Processing sequence polarbear ...
    Processing sequence skating ...
    Processing sequence sphere ...
    Processing sequence sunshade ...
    Processing sequence surfing ...
    Processing sequence torus ...
    Processing sequence trellis ...
    Processing sequence tunnel ...
    Processing sequence woman ...
error: structure has no member 'lineSpacing'
error: called from:
error:   /usr/share/octave/packages/general-1.3.4/@inputParser/subsref.m at line 61, column 7
error:   /usr/share/octave/packages/general-1.3.4/@inputParser/subsref.m at line 34, column 11
error:   /home/davis/temp/new-vot-toolkit/utilities/timeline.m at line 48, column 13
error:   /home/davis/temp/new-vot-toolkit/report/report_failures.m at line 44, column 9
error:   /home/davis/temp/new-vot-toolkit/report/report_challenge.m at line 120, column 23
error:   /home/davis/temp/new-vot-toolkit/working_dir/run_analysis.m at line 15, column 1
```

**Comment by lukacu** [comment]
Ok, it looks that more functions have different signatures in Octave. I will try to set up another workspace and run everything myself, but I will probably do it tomorrow.

**Comment by lukacu** [comment]
I have updated `timeline.m` yesterday, does it work now? Otherwise the ranking analysis is apparently working, the error is in failure analysis, which you can comment out.

**Comment by davisking** [comment]
Looks like it's working.  When I run it now I don't get any errors and there are html files in the reports folder showing the results.  However, none of the images were generated.  

I almost forgot that I still had that call to unqiue commented out as well (in /home/davis/temp/new-vot-toolkit/tracker/create_trackers.m at line 23).  That's still an error if I revert the code back to what is currently in github.

**Comment by lukacu** [comment]
Yes, that is another issue that I will attend to (I will keep the issue opened). As for the images, I have said before that the analysis part was never tested completely in Octave so there may be a problem with image generation. I have to verify if Octave even supports off-screen rendering the way it is done now.

**Comment by davisking** [comment]
No worries.  The most important stuff seems to be working now :)

**Comment by lukacu** [comment]
How about #33? Or did you use the old integration approach instead?

**Comment by davisking** [comment]
I used the old integration approach.

**Comment by lukacu** [comment]
However, none of the images were generated. 

Regarding this issue, I have looked into it and apparently the problem is in Octave rendering backend that [does not work with figures that are not visible on screen](https://savannah.gnu.org/bugs/?33180). The issue should be fixed in newer versions, but this will probably get into repositories slowly (at least on Linux). There is [a workaround](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740449), but I have not managed to get it working so far.

**Comment by lukacu** [comment]
I can confirm that running command `graphics_toolkit gnuplot` (and having gnuplot installed) before running the analysis (or any other script that renders plots off screen) is a viable workaround for now. This is only needed if do not have the most recent versions of Octave that have the issue fixed (hopefully).

**Comment by davisking** [comment]
Cool.  Thanks for looking into this :)

**Comment by bjanssen** [comment]
`run_analysis` works for me in octave after the fix in PR #93

**Comment by lukacu** [comment]
I have merged the PR so I assume I can also close this issue.
